### ISSUE TITLE
[Request] Port ff2_sarysapub3 subplugin to ff2r

### ISSUE THREAD

**Issue by komisz01** [M60TM/FF2R-Sandy-Abilities#3]
If it's possible. . .
:3

**Comment by komisz01** [comment]
Or suggest an ams plugin that I can use in ff2r

**Comment by M60TM** [comment]
I suggest to use [BatFoxKid's AMS in ff2r_epic_abilities](https://github.com/Batfoxkid/Freak-Fortress-2-Rewrite/blob/main/addons/sourcemod/scripting/ff2r_epic_abilities.sp). Because it is combination of `ff2_doability` and `ability_management_system` in `ff2_sarysapub3`. It allows you to make config more easier.
